import time


def start_decorator(function):
    print('H', end='')
    time.sleep(0.1)
    print('e', end='')
    time.sleep(0.1)
    print('l', end='')
    time.sleep(0.1)
    print('l', end='')
    time.sleep(0.1)
    print('o', end=' ')
    time.sleep(0.1)

    print('i', end='')
    time.sleep(0.1)
    print('n', end='')
    time.sleep(0.1)
    print('v', end='')
    time.sleep(0.1)
    print('e', end='')
    time.sleep(0.1)
    print('s', end='')
    time.sleep(0.1)
    print('t', end='')
    time.sleep(0.1)
    print('o', end='')
    time.sleep(0.1)
    print('r', end='')
    time.sleep(0.1)
    print('!')
    time.sleep(0.1)

    print('l', end='')
    time.sleep(0.1)
    print('e', end='')
    time.sleep(0.1)
    print('t', end='')
    time.sleep(0.1)
    print("'", end='')
    time.sleep(0.1)
    print('s', end=' ')
    time.sleep(0.1)

    print('g', end='')
    time.sleep(0.1)
    print("o", end='')
    time.sleep(0.1)
    print('?')
    time.sleep(0.2)
    print('.', end='')
    time.sleep(0.2)
    print('.', end='')
    time.sleep(0.2)
    print('.')
    time.sleep(0.2)
    print('.', end='')
    time.sleep(0.2)
    print('.', end='')
    time.sleep(0.2)
    print('.')
    time.sleep(0.2)
    function()


def download():
    print('.', end='')
    time.sleep(0.1)
    print('.', end='')
    time.sleep(0.1)
    print('.')
    time.sleep(0.1)
    print('.', end='')
    time.sleep(0.1)
    print('.', end='')
    time.sleep(0.1)
    print('.')
    time.sleep(0.2)
